# Generated by Django 3.2 on 2021-04-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210429_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id_1',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.post'),
        ),
    ]
